### ISSUE TITLE
Release 1.7 breaks compatibilty with older ones

### ISSUE THREAD

**Issue by hvelarde** [plone/plone.tiles#13]
As described in https://github.com/plone/plone.tiles/commit/dcd8adbf343727cd5a8c5576962b37709c3ccfb9

**Comment by datakurre** [comment]
@hvelarde It was supposed to be backwards compatible. I check early next week, if I can restore cover support with better default adapters. If I cannot, I can re-release the latest 1.6.x as 1.7.1 and 1.7.0 as 2.0.0.

**Comment by datakurre** [comment]
@hvelarde I now know the backwards incompatibility with cover and it was completely unnecessary. I'll release 1.7.1 soonish (Monday latest) and check that cover branch runs.

**Comment by hvelarde** [comment]
thank you, @datakurre; you rock!

**Comment by datakurre** [comment]
Fixed with 1.7.1 release.
