### ISSUE TITLE
Which Plone version is targeted by master?

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.tiles#8]
I have just created a 1.4.x branch and have updated coredev 5.0 to use this: master seems to have too big changes.
But `setup.py` on master has classifiers for Plone 4.2, 4.3 and 5.0. I like having those numbers correct. Do we still wish to claim compatibility with those versions?
I would be inclined to only keep Plone 5.0 in there. Note that we cannot yet add 5.1, because this is not yet a known PyPI classifier.

**Comment by datakurre** [comment]
@mauritsvanrees What kind of issues there were with the master (1.5.x and upcoming 1.6.x)? Tests have been passing for all 4.2, 4.3 and 5.0 https://travis-ci.org/plone/plone.tiles I see nothing here, which prevents compatibility with 4.x. IMHO, only when the first backwards incompatible feature appears, we should make plone.tiles 2.0 and drop 4.x support.

**Comment by mauritsvanrees** [comment]
I have not seen issues. But coredev 5.0 still pins 1.4.0, which is a year (minus two days) old. Since then, 1.5.0, 1.5.1 and 1.5.2 have been released but no one has updated the pin in coredev.
Recently Johannes added plone.tiles to the checkouts in 5.1, but in versions.cfg it was still 1.4.0, which I afterwards updated to 1.5.2. That started me wondering about which version is meant to be used in which Plone.
BTW, plone.tiles is not used or tested in coredev, though having a correct pin there is of course good.

So: looks like it is fine to keep using master and the last release in coredev 5.0 and 5.1.  (4.3 does not mention this package.) Fine with me.
Could you make a new release and update coredev? I can do it too if you like.

**Comment by datakurre** [comment]
@mauritsvanrees I released 1.6 (not sure, if it should have been 1.6.0 though). Please, fix coredev, when you can. 

plone.tiles in cordev is probably remains of some Deco or Mosaic related sprint (at least we left plip-placeholder from Mosaic sprint). AFAIK, no Plone core packages have ever depended on it. Yet, we should make a PLIP for 5.2 soon... (at least at September sprint if not earlier).

**Comment by mauritsvanrees** [comment]
Nowadays I would prefer 1.6.0, because this signals to me that a package is probably using semantic versioning and that the next bugfix release will be 1.6.1.  With 1.6 I am not sure if a future 1.7 release will be a bugfix release or if it may contain new features.
But don't worry about it. :-)
Thanks, I have updated coredev 5.0 and 5.1 to use this new release.
