### ISSUE TITLE
Tile registration with non-existing template must fail.

### ISSUE THREAD

**Issue by jensens** [plone/plone.tiles#9]
If a tile is registered with a non-existing template this is currently silently ignored. If the template does not exist - e.g. due to a typo - registration must fail.

**Comment by gforcada** [comment]
Where do you see that this does not happen? With Zope 2.13.24 (on Plone 5.1) I see that this is already taken care on https://github.com/zopefoundation/Zope/blob/2.13/src/Products/Five/browser/metaconfigure.py#L82-L85
